_is_protocol: false
data_dict: null
dataset: visnav
dt_frames: 0.05
dt_max: 52
dt_population_size: 28
dt_speed: 0.2
dt_vars: 0.05
frame_block_size: 46
frame_memory: 5.0
id_block_size: 100
id_population_size: 2025
id_prev_block_size: 300
idx: 0
interval: 0
intervals: null
itos_speed: null
min_interval: 0.3
population_size: 2025
pred: false