batch_size: 224
betas: !!python/tuple
- 0.9
- 0.95
clip_norm: 1.0
dataset: visnav
decay_weights: true
dist: false
grad_norm_clip: 1.0
learning_rate: 0.0001
loss_bprop: null
lr_decay: true
mode: predict
no_pbar: false
num_workers: 4
patience: 3
plot_raster: false
save_every: 1000
show_grads: false
shuffle: true
weight_decay: 1.0
