attn_pdrop: 0.2
b_drop: 0.45
behavior_block_size: 15
block_size: 446
class_weights: null
clip_embd: 3
clip_temp: 0.25
contrastive: false
conv_layer: true
dt: 0.025
embd_pdrop: 0.2
epoch: 757
freeze_weights: null
id_block_size: 100
id_drop: 0.35
im_drop: 0.35
kernel_size: null
n_embd: 256
clip_emb: 
n_embd_frames: 64
n_head: 8
n_state_history_layers: 8
n_state_layers: 8
n_stimulus_layers: 0
n_behavior_layers: 2
p_sparse: null
pos_emb: false
pos_pdrop: 0.2
pretrain: false
prev_id_block_size: 300
resid_pdrop: 0.2
resnet_backbone: false
self_att_layers: 8
sparse_mask: false
sparse_topk: null
sparse_topk_frame: null
sparse_topk_id: null
sparse_topk_prev_id: null
start_prune: 30
temp_emb: true
temp_pdrop: 0.2
vit_encoder: false
window: 0.025
window_prev: 0.1
window_behavior: 0.025
dt_vars: 0.025
frame_window: null
