_is_protocol: false
behavior_block_size: 0
behavior_feats: null
behavior_vars: null
block_size: 446
data_dict: null
dataset: visnav
dt: 0.005
dt_frames: 0.05
dt_max: 52
dt_population_size: 28
dt_speed: 0.2
dt_vars: 0.05
frame_block_size: 46
frame_memory: 4.0
frame_window: 0.2
id_block_size: 100
id_population_size: 2204
id_prev_block_size: 300
idx: 0
interval: 0
intervals: null
itos_speed: null
min_interval: 0.3
population_size: 2204
pred: false
predict_behavior: false
samples_per_behavior: 0
stoi_speed: null
window: 0.05
window_behavior: 0.05
window_prev: 0.25
