dropout:
  attn: 0.2
  embd: 0.2
  pos: 0.2
  resid: 0.2
  temp: 0.2
  b: 0.45
  id: 0.35
  im: 0.35

block_size:
  behavior: 15
  frame: 446
  id: 100
  prev_id: 300

layers:
  state_history: 8
  state: 8
  stimulus: 0
  self_att: 8
  modalities:
    n_behavior: 25

sparse:
  p: null
  mask: false
  topk: null
  topk_frame: null
  topk_id: null
  topk_prev_id: null

window:
  frame: 0.2
  curr: 0.05
  prev: 0.25
  speed: 0.05

predict:
  speed:
    objective: 'regression'

frame_encoder:
  conv_layer: true
  kernel_size: [4, 5, 5]
  n_embd: 256
  n_embd_frames: 64
  resnet_backbone: false

contrastive:
  contrastive: false
  vars: ['id', 'frames', 'speed']
  clip_embd: 1024
  clip_temp: 0.5

resolution:
  dt: 0.01
  speed: 0.1
  frames: 0.05

# GRU, MLP experiments
mlp_only: true
gru_only: false

# Rest of your parameters
class_weights: null
epoch: 757
freeze_weights: null
n_head: 8
n_embd: 256
pos_emb: false
pretrain: false
start_prune: 30
temp_emb: true
vit_encoder: true
vocab_size: 2204
