batch_size: 16
betas: !!python/tuple
- 0.9
- 0.95
block_size: 1150
ckpt_path: /data5/antonis/neuroformer/models/tensorboard/LRN/channel/window:0.5_prev:19.5_smooth/sparse_f:None_id:None/w:0.5_wp:19.5/6_Cont:True_window:0.5_f_window:20_df:0.1_blocksize:150_conv_False_shuffle:True_batch:12_sparse_(None_None)_blocksz1150_pos_emb:False_temp_emb:True_drop:0.35_dt:True_2.0_197_max0.1_(8,
  8, 8)_8_256.pt
clip_norm: 1.0
dataset: NaturalStim
decay_weights: true
dist: true
final_tokens: 2649960000
grad_norm_clip: 1.0
id_block_size: 150
learning_rate: 0.0001
lr_decay: false
max_epochs: 300
mode: predict
no_pbar: false
num_workers: 4
patience: 3
plot_raster: false
save_every: 1000
show_grads: false
shuffle: true
warmup_tokens: 80000000.0
weight_decay: 0.2