_is_protocol: false
behavior_block_size: 0
behavior_feats: null
behavior_vars: null
block_size: 446
data_dict: null
dataset: Combo3_V1AL
dt: 0.01
dt_vars: 0.05
frame_block_size: 46
id_block_size: 55
id_population_size: 389
id_prev_block_size: 100
intervals: null
itos_speed: null
min_interval: 0.3
population_size: 389
pred: false
predict_behavior: false
stoi_speed: null
frame_window: 0.15
