batch_size: 128
betas: !!python/tuple
- 0.9
- 0.95
clip_norm: 1.0
dataset: higher_order
decay_weights: true
dist: false
final_tokens: 512075000
grad_norm_clip: 1.0
id_block_size: 55
id_population_size: 389
id_prev_block_size: 100
learning_rate: 0.0001
loss_bprop: null
lr_decay: true
max_epochs: 250
mode: predict
no_pbar: false
num_workers: 4
patience: 3
plot_raster: false
save_every: 1000
show_grads: false
shuffle: true
warmup_tokens: 800000.0
weight_decay: 1.0
