_is_protocol: false
behavior_block_size: 0
behavior_feats: null
behavior_vars: null
block_size: 110
data_dict: null
dataset: Combo3_V1AL
dt: 0.01
dt_frames: 0.05
dt_max: 27
dt_population_size: 28
dt_speed: 0.2
dt_vars: 0.05
frame_block_size: 0
frame_memory: 4.0
frame_window: 0.25
id_block_size: 55
id_population_size: 389
id_prev_block_size: 55
idx: 0
interval: 0
intervals: null
itos_speed: null
labels: true
min_interval: 0.3
population_size: 389
pred: false
predict_behavior: null
samples_per_behavior: 0
stoi_speed: null
window: 0.05
window_behavior: 0.05
window_prev: 0.25
