attn_pdrop: 0.2
b_drop: 0.45
behavior_block_size: 0
block_size: 110
class_weights: null
clip_emb: 1024
clip_temp: 0.5
contrastive: false
conv_layer: true
dt: 0.01
embd_pdrop: 0.2
epoch: 859
frame_block_size: 0
frame_window: 0.25
freeze_weights: null
id_block_size: 55
id_drop: 0.1
id_vocab_size: 389
ignore_index_dt: 27
ignore_index_id: 388
im_drop: 0.1
n_behavior: null
n_behavior_layers: 0
n_dt: 28
n_embd: 256
n_embd_frames: 64
n_head: 8
n_state_history_layers: 8
n_state_layers: 8
n_stimulus_layers: 8
p_sparse: null
padding_size: 0
pos_emb: false
pos_pdrop: 0.2
predict_behavior: false
pretrain: false
prev_id_block_size: 55
resid_pdrop: 0.2
resnet_backbone: false
self_att_layers: 0
sparse_mask: false
sparse_topk: null
sparse_topk_frame: null
sparse_topk_id: null
sparse_topk_prev_id: null
start_prune: 30
temp_emb: true
temp_pdrop: 0.2
vit_encoder: true
vocab_size: 389
window: 0.05
window_prev: 0.25
