batch_size: 64
betas: !!python/tuple
- 0.9
- 0.95
block_size: 110
ckpt_path: ./models/tensorboard/Combo3_V1AL/downstream_final/pretrain/past_state_True_visualTrue_contrastive_Truefreeze_False/randperm_False/Big_fixed_noself-att_2/sparse_f:None_id:None/w:0.05_wp:0.25/Cont:False_window:0.05_f_window:0.25_df:0.01_blocksize:55_conv_True_shuffle:True_batch:64_sparse_(None_None)_blocksz110_pos_emb:False_temp_emb:True_drop:0.1_dt:True_2.0_27_max0.01_(8,
  8, 8)_8_256.pt
clip_norm: 1.0
dataset: higher_order
decay_weights: true
dist: false
final_tokens: 279345000
grad_norm_clip: 1.0
id_block_size: 55
learning_rate: 0.0001
loss_bprop: null
lr_decay: true
max_epochs: 250
mode: predict
no_pbar: false
num_workers: 4
patience: 3
plot_raster: false
save_every: 20
show_grads: false
shuffle: true
warmup_tokens: 80000.0
weight_decay: 0.1
