_is_protocol: false
behavior_block_size: 0
behavior_feats: null
behavior_vars: null
block_size: 40
data_dict: null
dataset: Combo3_SimNeu3D
dt: 0.01
dt_frames: 0.05
dt_max: 27
dt_population_size: 28
dt_speed: 0.2
dt_vars: 0.05
frame_block_size: 0
frame_window: 1
id_block_size: 20
id_population_size: 363
id_prev_block_size: 20
idx: 0
interval: 0
intervals: null
itos_speed: null
labels: true
min_interval: 0.35
population_size: 363
pred: false
predict_behavior: false
resample_data: false
samples_per_behavior: 0
stoi_speed: null
window: 0.1
window_behavior: null
window_prev: null
