batch_size: 512
betas: !!python/tuple
- 0.9
- 0.95
block_size: 40
ckpt_path: ./models/tensorboard/Combo3_SimNeu3D/None/sparse_f:None_id:None/w:0.1_wp:0.25/Cont:True['id',
  'frames']_window:0.1_f_window:0.1_df:0.01_blocksize:55_conv_True_shuffle:True_batch:512_sparse_(None_None)_blocksz40_pos_emb:False_temp_emb:True_drop:0.35_dt:True_2.0_27_max0.01_(4,
  4, 4)_4_256.pt
clip_norm: 1.0
dataset: Combo3_V1AL
decay_weights: true
dist: true
final_tokens: 9228540000
get_latents: false
grad_norm_clip: 1.0
id_block_size: 20
learning_rate: 0.0001
loss_bprop: null
lr_decay: true
max_epochs: 1000
mode: predict
no_pbar: false
num_workers: 4
patience: 3
plot_raster: false
save_every: 20
show_grads: false
shuffle: true
warmup_tokens: 80000.0
weight_decay: 0.1
