_is_protocol: false
block_size: 1150
data_dict: null
dataset: LRN
dt: 0.1
dt_frames: 0.1
dt_max: 197
dt_population_size: 198
frame_block_size: 200
frame_memory: 20
frame_window: 20
frames: null
id_block_size: 150
id_population_size: 1003
id_prev_block_size: 800
idx: 0
interval: 0
min_interval: 20.0
population_size: 1003
pred: false
size: 851234
window: 0.5
window_prev: 19.5
