attn_pdrop: 0.2
block_size: 1150
class_weights: null
clip_emb: 1024
clip_temp: 0.5
contrastive: false
conv_layer: false
data_size: 823194
dataset: LRN
dt: 0.1
embd_pdrop: 0.2
epoch: 101
frame_block_size: 200
frame_window: 20
id_block_size: 150
id_drop: 0.35
id_vocab_size: 1003
ignore_index_dt: 197
ignore_index_id: 1002
im_drop: 0.35
n_dt: 198
n_embd: 256
n_embd_frames: 1000
n_head: 1
n_layer: 10
n_state_history_layers: 4
n_state_layers: 4
n_stimulus_layers: 4
p_reduce: 20
p_sparse: 0.25
pos_emb: false
pos_pdrop: 0.2
pretrain: false
prev_id_block_size: 800
resid_pdrop: 0.2
resnet_backbone: false
self_att_layers: 8
sparse_mask: false
sparse_topk: null
sparse_topk_frame: null
sparse_topk_id: null
sparse_topk_id_prev: null
sparse_topk_prev_id: null
start_prune: 30
temp_emb: true
temp_pdrop: 0.2
vit_encoder: true
vocab_size: 1003
window: 0.5
window_prev: 19.5
